// <auto-generated />
using System;
using Md2.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Md2.Migrations
{
    [DbContext(typeof(MdDbContext))]
    [Migration("20211210014450_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Md2.Dal.MdRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("Md2.Dal.MdResolvedReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRelativePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.ToTable("ResolvedReferences");
                });

            modelBuilder.Entity("Md2.Dal.MdResolvedReference", b =>
                {
                    b.HasOne("Md2.Dal.MdRepo", "Repo")
                        .WithMany()
                        .HasForeignKey("RepoId");

                    b.Navigation("Repo");
                });
#pragma warning restore 612, 618
        }
    }
}
